@startuml
'https://plantuml.com/class-diagram

component cli {
    package command {
        class ConfluenceToAnkiCommand {
            -confluencePageId : String
            +call() : Integer //contains the business logic
            +{static} main()
        }
    }
}

component conversion {
    class ConverionController {
        +convertConfluencePageToAnkiImportableCsv(pageId : String)
    }
}

ConfluenceToAnkiCommand --> ConverionController

@enduml